export const customers = [
    {
        id: 1,
        username: 'Brayan.v',
        email: 'Brayan@Primates.com',
        firstName: 'Brayan',
        lastName: 'Velez',
        middleName: '',
        storeId: 2,
        position: 'Domiciliario',
        numOrders: 5,
        walletBalance: 5255,
        revenue: 3450,
        billing: {
            firstName: 'Brayan',
            lastName: 'Velez',
            middleName: '',
            company: 'Primates',
            email: 'Brayan@Primates.com',
            phone: '(034) 231-0332',
            country: {name: 'Armenia', code: 'Quindio'},
            city: 'Armenia',
            state: 'Quindio',
            zip: '90201',
            address: 'Palos Verdes Peninsula'
        }
    },
    {
        id: 2,
        username: 'Andres.79',
        email: 'Arango@primates.com',
        firstName: 'Andres',
        lastName: 'Arango',
        middleName: '',
        storeId: 1,
        position: 'Domiciliario',
        numOrders: 5,
        walletBalance: 8055,
        revenue: 7200,
        billing: {
            firstName: 'Andres',
            lastName: 'Arango',
            middleName: '',
            company: 'Primates',
            email: 'Arango@primates.com',
            phone: '(033) 457-2308',
            country: {name: 'Armenia', code: 'Quindio'},
            city: 'Armenia',
            state: 'Quindio',
            zip: '90201',
            address: 'Palos Verdes Peninsula'
        }
    },
    {
        id: 3,
        username: 'ashley',
        email: 'ashley@primates.com',
        firstName: 'Ashley',
        lastName: 'Cortez',
        middleName: '',
        storeId: 1,
        position: 'Domiciliario',
        numOrders: 5,
        walletBalance: 17200,
        revenue: 2200,
        billing: {
            firstName: 'Ashley',
            lastName: 'Cortez',
            middleName: '',
            company: 'Primates',
            email: 'ashley@primates.com',
            phone: '(212) 457-2308',
            country: {name: 'Armenia', code: 'Quindio'},
            city: 'Armenia',
            state: 'Quindio',
            zip: '90201',
            address: 'Palos Verdes Peninsula'
        }
    },
    {
        id: 4,
        username: 'Juliana.a',
        email: 'Juliana@primates.com',
        firstName: 'Juliana',
        lastName: 'Arango',
        middleName: '',
        storeId: 2,
        position: 'Domiciliario',
        numOrders: 5,
        walletBalance: 9480,
        revenue: 1470,
        billing: {
            firstName: 'Juliana',
            lastName: 'Arango',
            middleName: '',
            company: 'Primates5',
            email: 'Juliana@primates.com',
            phone: '(212) 457-2308',
            country: {name: 'Armenia', code: 'Quindio'},
            city: 'Armenia',
            state: 'Quindio',
            zip: '90201',
            address: 'Palos Verdes Peninsula'
        }
    },
    {
        id: 5,
        username: 'Luisa.m',
        email: 'Luisa@primates.com',
        firstName: 'Luisa',
        lastName: 'Montes',
        middleName: '',
        storeId: 1,
        position: 'Domiciliario',
        numOrders: 5,
        walletBalance: 6200,
        revenue: 3250,
        billing: {
            firstName: 'Luisa',
            lastName: 'Montes',
            middleName: '',
            company: 'Primates4',
            email: 'Luisa@primates.com',
            phone: '(212) 457-2308',
            country: {name: 'Armenia', code: 'Quindio'},
            city: 'Armenia',
            state: 'Quindio',
            zip: '90201',
            address: 'Palos Verdes Peninsula'
        }
    },
    {
        id: 6,
        username: 'Ademair.s',
        email: 'Ademair@primates.com',
        firstName: 'Ademair',
        lastName: 'Sandler',
        middleName: '',
        storeId: 2,
        position: 'Domiciliario',
        numOrders: 5,
        walletBalance: 7580,
        revenue: 2950,
        billing: {
            firstName: 'Ademair',
            lastName: 'Sandler',
            middleName: '',
            company: 'Primates1',
            email: 'Ademair@primates.com',
            phone: '(212) 457-2308',
            country: {name: 'Armenia', code: 'Quindio'},
            city: 'Armenia',
            state: 'Quindio',
            zip: '90201',
            address: 'Palos Verdes Peninsula'
        }
    },
    {
        id: 7,
        username: 'tereza.s',
        email: 'tereza@primates.com',
        firstName: 'Tereza',
        lastName: 'Soto',
        middleName: '',
        storeId: 2,
        position: 'Domiciliario',
        numOrders: 5,
        walletBalance: 5240,
        revenue: 1095,
        billing: {
            firstName: 'Tereza',
            lastName: 'Soto',
            middleName: '',
            company: 'Primates3',
            email: 'tereza@primates.com',
            phone: '(212) 457-2308',
            country: {name: 'Armenia', code: 'Quindio'},
            city: 'Armenia',
            state: 'Quindio',
            zip: '90201',
            address: 'Palos Verdes Peninsula'
        }
    },
    {
        id: 8,
        username: 'michael.b',
        email: 'michael@primates.com',
        firstName: 'Michael',
        lastName: 'Botero',
        middleName: '',
        storeId: 2,
        position: 'Domiciliario',
        numOrders: 5,
        walletBalance: 7340,
        revenue: 4580,
        billing: {
            firstName: 'Michael',
            lastName: 'Botero',
            middleName: '',
            company: 'Primates3',
            email: 'michael@primates.com',
            phone: '(212) 457-2308',
            country: {name: 'Armenia', code: 'Quindio'},
            city: 'Armenia',
            state: 'Quindio',
            zip: '90201',
            address: 'Palos Verdes Peninsula'
        }
    }
]